// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cortex/ent/category"
	"cortex/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CategoryUpdate is the builder for updating Category entities.
type CategoryUpdate struct {
	config
	hooks    []Hook
	mutation *CategoryMutation
}

// Where appends a list predicates to the CategoryUpdate builder.
func (_u *CategoryUpdate) Where(ps ...predicate.Category) *CategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *CategoryUpdate) SetUUID(v string) *CategoryUpdate {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableUUID(v *string) *CategoryUpdate {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CategoryUpdate) SetCreatedAt(v time.Time) *CategoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableCreatedAt(v *time.Time) *CategoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CategoryUpdate) SetUpdatedAt(v time.Time) *CategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *CategoryUpdate) SetSlug(v string) *CategoryUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableSlug(v *string) *CategoryUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *CategoryUpdate) SetLabel(v string) *CategoryUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableLabel(v *string) *CategoryUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CategoryUpdate) SetDescription(v string) *CategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableDescription(v *string) *CategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CategoryUpdate) ClearDescription() *CategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *CategoryUpdate) SetCreatorID(v int) *CategoryUpdate {
	_u.mutation.ResetCreatorID()
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableCreatorID(v *int) *CategoryUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// AddCreatorID adds value to the "creator_id" field.
func (_u *CategoryUpdate) AddCreatorID(v int) *CategoryUpdate {
	_u.mutation.AddCreatorID(v)
	return _u
}

// ClearCreatorID clears the value of the "creator_id" field.
func (_u *CategoryUpdate) ClearCreatorID() *CategoryUpdate {
	_u.mutation.ClearCreatorID()
	return _u
}

// SetApproverID sets the "approver_id" field.
func (_u *CategoryUpdate) SetApproverID(v int) *CategoryUpdate {
	_u.mutation.ResetApproverID()
	_u.mutation.SetApproverID(v)
	return _u
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableApproverID(v *int) *CategoryUpdate {
	if v != nil {
		_u.SetApproverID(*v)
	}
	return _u
}

// AddApproverID adds value to the "approver_id" field.
func (_u *CategoryUpdate) AddApproverID(v int) *CategoryUpdate {
	_u.mutation.AddApproverID(v)
	return _u
}

// ClearApproverID clears the value of the "approver_id" field.
func (_u *CategoryUpdate) ClearApproverID() *CategoryUpdate {
	_u.mutation.ClearApproverID()
	return _u
}

// SetUpdaterID sets the "updater_id" field.
func (_u *CategoryUpdate) SetUpdaterID(v int) *CategoryUpdate {
	_u.mutation.ResetUpdaterID()
	_u.mutation.SetUpdaterID(v)
	return _u
}

// SetNillableUpdaterID sets the "updater_id" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableUpdaterID(v *int) *CategoryUpdate {
	if v != nil {
		_u.SetUpdaterID(*v)
	}
	return _u
}

// AddUpdaterID adds value to the "updater_id" field.
func (_u *CategoryUpdate) AddUpdaterID(v int) *CategoryUpdate {
	_u.mutation.AddUpdaterID(v)
	return _u
}

// ClearUpdaterID clears the value of the "updater_id" field.
func (_u *CategoryUpdate) ClearUpdaterID() *CategoryUpdate {
	_u.mutation.ClearUpdaterID()
	return _u
}

// SetDeleterID sets the "deleter_id" field.
func (_u *CategoryUpdate) SetDeleterID(v int) *CategoryUpdate {
	_u.mutation.ResetDeleterID()
	_u.mutation.SetDeleterID(v)
	return _u
}

// SetNillableDeleterID sets the "deleter_id" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableDeleterID(v *int) *CategoryUpdate {
	if v != nil {
		_u.SetDeleterID(*v)
	}
	return _u
}

// AddDeleterID adds value to the "deleter_id" field.
func (_u *CategoryUpdate) AddDeleterID(v int) *CategoryUpdate {
	_u.mutation.AddDeleterID(v)
	return _u
}

// ClearDeleterID clears the value of the "deleter_id" field.
func (_u *CategoryUpdate) ClearDeleterID() *CategoryUpdate {
	_u.mutation.ClearDeleterID()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *CategoryUpdate) SetApprovedAt(v time.Time) *CategoryUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableApprovedAt(v *time.Time) *CategoryUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *CategoryUpdate) ClearApprovedAt() *CategoryUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CategoryUpdate) SetDeletedAt(v time.Time) *CategoryUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableDeletedAt(v *time.Time) *CategoryUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CategoryUpdate) ClearDeletedAt() *CategoryUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CategoryUpdate) SetStatus(v category.Status) *CategoryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableStatus(v *category.Status) *CategoryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMeta sets the "meta" field.
func (_u *CategoryUpdate) SetMeta(v map[string]interface{}) *CategoryUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *CategoryUpdate) ClearMeta() *CategoryUpdate {
	_u.mutation.ClearMeta()
	return _u
}

// Mutation returns the CategoryMutation object of the builder.
func (_u *CategoryUpdate) Mutation() *CategoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CategoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CategoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := category.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CategoryUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := category.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Category.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := category.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Category.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := category.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "Category.creator_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := category.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Category.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(category.Table, category.Columns, sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(category.FieldUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(category.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(category.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(category.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(category.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(category.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(category.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(category.FieldCreatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatorID(); ok {
		_spec.AddField(category.FieldCreatorID, field.TypeInt, value)
	}
	if _u.mutation.CreatorIDCleared() {
		_spec.ClearField(category.FieldCreatorID, field.TypeInt)
	}
	if value, ok := _u.mutation.ApproverID(); ok {
		_spec.SetField(category.FieldApproverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedApproverID(); ok {
		_spec.AddField(category.FieldApproverID, field.TypeInt, value)
	}
	if _u.mutation.ApproverIDCleared() {
		_spec.ClearField(category.FieldApproverID, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdaterID(); ok {
		_spec.SetField(category.FieldUpdaterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdaterID(); ok {
		_spec.AddField(category.FieldUpdaterID, field.TypeInt, value)
	}
	if _u.mutation.UpdaterIDCleared() {
		_spec.ClearField(category.FieldUpdaterID, field.TypeInt)
	}
	if value, ok := _u.mutation.DeleterID(); ok {
		_spec.SetField(category.FieldDeleterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeleterID(); ok {
		_spec.AddField(category.FieldDeleterID, field.TypeInt, value)
	}
	if _u.mutation.DeleterIDCleared() {
		_spec.ClearField(category.FieldDeleterID, field.TypeInt)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(category.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(category.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(category.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(category.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(category.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(category.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(category.FieldMeta, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{category.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CategoryUpdateOne is the builder for updating a single Category entity.
type CategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CategoryMutation
}

// SetUUID sets the "uuid" field.
func (_u *CategoryUpdateOne) SetUUID(v string) *CategoryUpdateOne {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableUUID(v *string) *CategoryUpdateOne {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CategoryUpdateOne) SetCreatedAt(v time.Time) *CategoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableCreatedAt(v *time.Time) *CategoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CategoryUpdateOne) SetUpdatedAt(v time.Time) *CategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *CategoryUpdateOne) SetSlug(v string) *CategoryUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableSlug(v *string) *CategoryUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *CategoryUpdateOne) SetLabel(v string) *CategoryUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableLabel(v *string) *CategoryUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CategoryUpdateOne) SetDescription(v string) *CategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableDescription(v *string) *CategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CategoryUpdateOne) ClearDescription() *CategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *CategoryUpdateOne) SetCreatorID(v int) *CategoryUpdateOne {
	_u.mutation.ResetCreatorID()
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableCreatorID(v *int) *CategoryUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// AddCreatorID adds value to the "creator_id" field.
func (_u *CategoryUpdateOne) AddCreatorID(v int) *CategoryUpdateOne {
	_u.mutation.AddCreatorID(v)
	return _u
}

// ClearCreatorID clears the value of the "creator_id" field.
func (_u *CategoryUpdateOne) ClearCreatorID() *CategoryUpdateOne {
	_u.mutation.ClearCreatorID()
	return _u
}

// SetApproverID sets the "approver_id" field.
func (_u *CategoryUpdateOne) SetApproverID(v int) *CategoryUpdateOne {
	_u.mutation.ResetApproverID()
	_u.mutation.SetApproverID(v)
	return _u
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableApproverID(v *int) *CategoryUpdateOne {
	if v != nil {
		_u.SetApproverID(*v)
	}
	return _u
}

// AddApproverID adds value to the "approver_id" field.
func (_u *CategoryUpdateOne) AddApproverID(v int) *CategoryUpdateOne {
	_u.mutation.AddApproverID(v)
	return _u
}

// ClearApproverID clears the value of the "approver_id" field.
func (_u *CategoryUpdateOne) ClearApproverID() *CategoryUpdateOne {
	_u.mutation.ClearApproverID()
	return _u
}

// SetUpdaterID sets the "updater_id" field.
func (_u *CategoryUpdateOne) SetUpdaterID(v int) *CategoryUpdateOne {
	_u.mutation.ResetUpdaterID()
	_u.mutation.SetUpdaterID(v)
	return _u
}

// SetNillableUpdaterID sets the "updater_id" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableUpdaterID(v *int) *CategoryUpdateOne {
	if v != nil {
		_u.SetUpdaterID(*v)
	}
	return _u
}

// AddUpdaterID adds value to the "updater_id" field.
func (_u *CategoryUpdateOne) AddUpdaterID(v int) *CategoryUpdateOne {
	_u.mutation.AddUpdaterID(v)
	return _u
}

// ClearUpdaterID clears the value of the "updater_id" field.
func (_u *CategoryUpdateOne) ClearUpdaterID() *CategoryUpdateOne {
	_u.mutation.ClearUpdaterID()
	return _u
}

// SetDeleterID sets the "deleter_id" field.
func (_u *CategoryUpdateOne) SetDeleterID(v int) *CategoryUpdateOne {
	_u.mutation.ResetDeleterID()
	_u.mutation.SetDeleterID(v)
	return _u
}

// SetNillableDeleterID sets the "deleter_id" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableDeleterID(v *int) *CategoryUpdateOne {
	if v != nil {
		_u.SetDeleterID(*v)
	}
	return _u
}

// AddDeleterID adds value to the "deleter_id" field.
func (_u *CategoryUpdateOne) AddDeleterID(v int) *CategoryUpdateOne {
	_u.mutation.AddDeleterID(v)
	return _u
}

// ClearDeleterID clears the value of the "deleter_id" field.
func (_u *CategoryUpdateOne) ClearDeleterID() *CategoryUpdateOne {
	_u.mutation.ClearDeleterID()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *CategoryUpdateOne) SetApprovedAt(v time.Time) *CategoryUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableApprovedAt(v *time.Time) *CategoryUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *CategoryUpdateOne) ClearApprovedAt() *CategoryUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CategoryUpdateOne) SetDeletedAt(v time.Time) *CategoryUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableDeletedAt(v *time.Time) *CategoryUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CategoryUpdateOne) ClearDeletedAt() *CategoryUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CategoryUpdateOne) SetStatus(v category.Status) *CategoryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableStatus(v *category.Status) *CategoryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMeta sets the "meta" field.
func (_u *CategoryUpdateOne) SetMeta(v map[string]interface{}) *CategoryUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *CategoryUpdateOne) ClearMeta() *CategoryUpdateOne {
	_u.mutation.ClearMeta()
	return _u
}

// Mutation returns the CategoryMutation object of the builder.
func (_u *CategoryUpdateOne) Mutation() *CategoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the CategoryUpdate builder.
func (_u *CategoryUpdateOne) Where(ps ...predicate.Category) *CategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CategoryUpdateOne) Select(field string, fields ...string) *CategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Category entity.
func (_u *CategoryUpdateOne) Save(ctx context.Context) (*Category, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoryUpdateOne) SaveX(ctx context.Context) *Category {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CategoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := category.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := category.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Category.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := category.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Category.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := category.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "Category.creator_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := category.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Category.status": %w`, err)}
		}
	}
	return nil
}

func (_u *CategoryUpdateOne) sqlSave(ctx context.Context) (_node *Category, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(category.Table, category.Columns, sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Category.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, category.FieldID)
		for _, f := range fields {
			if !category.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != category.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(category.FieldUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(category.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(category.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(category.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(category.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(category.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(category.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(category.FieldCreatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatorID(); ok {
		_spec.AddField(category.FieldCreatorID, field.TypeInt, value)
	}
	if _u.mutation.CreatorIDCleared() {
		_spec.ClearField(category.FieldCreatorID, field.TypeInt)
	}
	if value, ok := _u.mutation.ApproverID(); ok {
		_spec.SetField(category.FieldApproverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedApproverID(); ok {
		_spec.AddField(category.FieldApproverID, field.TypeInt, value)
	}
	if _u.mutation.ApproverIDCleared() {
		_spec.ClearField(category.FieldApproverID, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdaterID(); ok {
		_spec.SetField(category.FieldUpdaterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdaterID(); ok {
		_spec.AddField(category.FieldUpdaterID, field.TypeInt, value)
	}
	if _u.mutation.UpdaterIDCleared() {
		_spec.ClearField(category.FieldUpdaterID, field.TypeInt)
	}
	if value, ok := _u.mutation.DeleterID(); ok {
		_spec.SetField(category.FieldDeleterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeleterID(); ok {
		_spec.AddField(category.FieldDeleterID, field.TypeInt, value)
	}
	if _u.mutation.DeleterIDCleared() {
		_spec.ClearField(category.FieldDeleterID, field.TypeInt)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(category.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(category.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(category.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(category.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(category.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(category.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(category.FieldMeta, field.TypeJSON)
	}
	_node = &Category{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{category.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
